package com.shopsense.client.gemini;

public interface GeminiClient {

    /**
     * Sends a text prompt to the Gemini API and returns the generated text
     * response.
     *
     * @param prompt The prompt to send to Gemini.
     * @return Raw text response generated by Gemini.
     */
    String generateContent(String prompt);
}
